<a href="https://colab.research.google.com/github/alveslim/AI-Engineering/blob/main/Ciencias_dados_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series ([10, 12, 13, 14, 20])

In [ ]:
num = (1+int(s[1]))
print(f"o numero da posicao 1o: {num}")

o numero da posicao 1o: 13

In [ ]:
s.describe().to_string()

count     5.000000
mean     13.800000
std       3.768289
min      10.000000
25%      12.000000
50%      13.000000
75%      14.000000
max      20.000000
dtype: float64

In [ ]:
# Exibe o resultado como uma tabela/DataFrame
s.describe().to_frame()

               0
count   5.000000
mean   13.800000
std     3.768289
min    10.000000
25%    12.000000
50%    13.000000
75%    14.000000
max    20.000000

problemmas ia:

classificacao -> se eh y ou z
agrupamente -> cachorro, gato, pessoa
regressao -> series

In [ ]:
s_custom = pd.Series ([12, 20, 22], index=['empresa_1', 'empresa_2', 'empresa_3'])

futurewarnig: diz que o futuramente algo do codigo nao ira funcionar.

In [ ]:
dic1 = {'ESTADO': ['Amazonas', 'Amapá', 'Acre'], 'SIGLA': ['AM', 'AP', 'AC'], 'CAPITAL': ['Manaus', 'Macapá', 'Rio Branco']}

In [ ]:
dados = pd.read_csv(/content/sample_data/mnist_test.csv)

SyntaxError: invalid syntax (3080702027.py, line 1)

Arquitetura Básica (Como funciona a integração)
1. Power Apps (Interface): O usuário preenche um formulário, seleciona parâmetros ou clica em um botão para enviar dados ou solicitar um relatório.
2. Power Automate (Orquestrador): Recebe o gatilho do Power Apps, coleta os dados necessários, aciona o script Python e devolve a resposta tratada para o Power Apps ou para um repositório (como SharePoint/Dataverse).
3. Python com Pandas (Processamento): Executa a limpeza, agregação ou manipulação pesada dos dados estruturados.

Opção 1: Usando o Power Automate Desktop (RPA)
Se o processamento puder acontecer em uma máquina local ou em uma máquina virtual (VM) dedicada:

---


• O Power Automate na nuvem chama um fluxo do Power Automate Desktop.

• O Power Automate Desktop possui uma ação nativa chamada "Executar script Python", que suporta versões modernas do Python e o uso de bibliotecas externas como o pandas.

• O fluxo lê os arquivos (Excel, CSV) ou recebe variáveis do Power Apps, o script Pandas processa os dados, e o resultado (print) é capturado pelo Power Automate para atualizar uma base de dados ou retornar ao aplicativo.

Opção 2: Usando uma API Cloud (Azure Functions / Webhook)
Se tudo precisa rodar 100% na nuvem sem depender de um computador ligado:


---


• Você cria uma função em Python hospedada no Azure Functions ou em um microsserviço que exponha uma API HTTP.

• Essa API aceita requisições POST com os dados ou o caminho dos arquivos, carrega o DataFrame do Pandas, faz o cálculo/transformação e retorna um JSON como resposta.

• No Power Automate, você usa a ação "HTTP" para enviar os dados do Power Apps para essa API e recebe o resultado de volta de forma instantânea para exibir na tela do usuário.

Passo a Passo Resumido para Implementação
1. Crie a tela no Power Apps: Insira um botão de comando (OnSelect) que utilize a função PowerAutomate.Run() para disparar o fluxo passando parâmetros em formato de texto ou JSON.
2. Configure o Power Automate: Adicione o gatilho "Power Apps (v2)", insira a etapa de conexão com o seu script (via API HTTP na nuvem ou via Power Automate Desktop).
3. Processe no Pandas: Escreva o código Python para importar o Pandas (import pandas as pd), tratar o Dataframe e retornar a saída formatada.
4. Retorne ao Power Apps: Use a ação final do Power Automate "Responder ao Power Apps" para devolver os dados processados e exibi-los em uma galeria ou rótulo na tela do aplicativo.
Se quiser detalhar a sua necessidade, me informe:
• Os dados que você manipula estão no Excel, SQL, SharePoint ou outra fonte?
• Você precisa de uma solução rodando 100% na nuvem ou pode usar um servidor/máquina local?
Posso desenhar um modelo de código ou fluxo específico para o seu cenário.